[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25,<26",
    "httpx>=0.28,<1",
    "pydantic-settings>=2.10,<3",
    "pymongo>=4.14,<5",
    "python-dotenv>=1.1,<2",
    "python-telegram-bot[job-queue]>=22,<23",
]
